name: Admin Build

on:
  push:
    paths:
      - "admin/rest/**"
    branches:
      - develop

jobs:
  build-frontend-admin:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
    env:
      NEXT_PUBLIC_REST_API_ENDPOINT: http://20.12.6.155:8000/api
      NEXT_PUBLIC_SHOP_URL: http://20.12.6.155:3003
      APPLICATION_MODE: production
      NEXT_PUBLIC_AUTH_TOKEN_KEY: AUTH_CRED
      NEXT_PUBLIC_DEFAULT_LANGUAGE: en
      NEXT_PUBLIC_ENABLE_MULTI_LANG: false
      NEXT_PUBLIC_AVAILABLE_LANGUAGES: en
      NEXT_PUBLIC_GOOGLE_MAP_API_KEY: ''
    steps:
    - uses: actions/checkout@v3
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          node_modules
        key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run Install Dependencies
      run: yarn
    - name: Run Install Shared
      run: yarn install:shared
    - name: Run Build Admin
      run: yarn build:admin-rest
    - name: Delete old server
      continue-on-error: true
      run: pm2 delete admin-rest
    - name: Start admin
      run: pm2 start "yarn start:admin-rest" --name admin-rest